development: &development
  protocol: 'http'
  host: localhost
  port: 5984 
  prefix: edrs
  suffix: hd
  username: root
  password: root.letusout!
  crtkey: 
  facility_code: 
  district_code: LL
  print_user:
  print_password:
  printer_name:

test:
  <<: *development
  suffix: test

production:
  <<: *development
  protocol: 'http'
  suffix:
